### ISSUE TITLE
Pip Install Numpy Compatibility 

### ISSUE THREAD

**Issue by Theo-Nelson** [Psy-Fer/blue-crab#11]
Dear Developers, 

During my latest installation of blue-crab, I received the following error:

``A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/bin/blue-crab", line 5, in <module>
    from src.blue_crab import main
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/src/blue_crab.py", line 16, in <module>
    import pod5 as p5
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pod5/__init__.py", line 17, in <module>
    from .api_utils import (
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pod5/api_utils.py", line 11, in <module>
    import pyarrow as pa
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/bin/blue-crab", line 5, in <module>
    from src.blue_crab import main
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/src/blue_crab.py", line 16, in <module>
    import pod5 as p5
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pod5/__init__.py", line 17, in <module>
    from .api_utils import (
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pod5/api_utils.py", line 11, in <module>
    import pyarrow as pa
  File "/athena/masonlab/scratch/users/thn4005/programs/blue-crab-venv/lib/python3.12/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/lib.pyx", line 36, in init pyarrow.lib
ImportError: numpy.core.multiarray failed to import``

Downgrading the numpy version in my virtual environment to numpy-1.26.4 from numpy 2.0.0 and pyArrow to pyarrow-14.0.2 from pyarrow-16.1.0 fixed the error. I thought I would submit this in case this is there is quick fix for this by recompiling the binary version available via pip. 

All the best!

Sincerely,
Theo

**Comment by Psy-Fer** [comment]
Hey , 

Thanks for this report.

Yep there as a new major release of numpy to version 2.0.0

I'll sort this out, but the quick solution for you is to downgrade your numpy library to less than 2

I'll have a proper fix in a few hours if you are happy to wait

Cheers,
James

**Comment by Psy-Fer** [comment]
Okay,

So the quick fix here is to install from source and modify the `requirements.txt` file so the first like with `numpy` on it looks like this

```
numpy==1.*
```

Then do a
```
pip install .
```

That will resolve the issues for now.

I've contact ONT to see if they have a fix for the issues with pod5.

Once they have figured things out on their end, I'll do what I need to do on our end to ensure compatibility.

Cheers,
James

**Comment by Psy-Fer** [comment]
Hey,

So ONT have released a new update to pod5, and we have released new wheels on pip compiled with numpy 2.0.0 for pyslow under version 1.2.0

So a new install of blue-crab should now work fine.

Please give it a try and let me know :) 

Cheers
James
